# Generated by Django 3.0.3 on 2020-04-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.PositiveIntegerField(blank=True)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
